backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    format: "frontmatter"
    folder: "assets/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Cover_image", name: "cover_image", widget: "image" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "movies"
    label: "Movies"
    format: "frontmatter"
    folder: "assets/content/movies"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Director", name: "director", widget: "string" }
      - { label: "Actors", name: "actors", widget: "list" }
      - { label: "Genre", name: "genre", widget: "list" }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "ReleaseDate", name: "date", widget: "datetime" }
      - { label: "Public", name: "public", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Poster", name: "poster", widget: "image" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Trailer", name: "trailer", widget: "string" }
© 2020 GitHub, Inc.
